# Generated by Django 3.0.5 on 2020-06-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200607_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(default='PhD', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='faculty',
            field=models.CharField(default='Engineering', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
