# Generated by Django 3.0.5 on 2020-06-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200610_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
