# Generated by Django 3.0.5 on 2020-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200610_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='profile_img'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
