# Generated by Django 3.0.5 on 2020-06-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0010_auto_20200604_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
