# Generated by Django 3.0.5 on 2020-06-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0012_auto_20200610_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document_exam',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='task',
            name='document_exam_answers',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
