# Generated by Django 3.0.5 on 2020-06-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0013_auto_20200611_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='document_exam',
        ),
        migrations.RemoveField(
            model_name='task',
            name='document_exam_answers',
        ),
    ]
