# Generated by Django 3.0.5 on 2020-06-10 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0014_auto_20200611_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklinks',
            name='link',
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='Answers file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='Exams file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='tasklinks',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
