# Generated by Django 3.0.5 on 2020-06-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0015_auto_20200611_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklinks',
            old_name='Answers file',
            new_name='answers_file',
        ),
        migrations.RenameField(
            model_name='tasklinks',
            old_name='Exams file',
            new_name='exam_file',
        ),
    ]
