# Generated by Django 3.0.5 on 2020-06-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qmain', '0016_auto_20200611_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklinks',
            name='answers_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=0.0, null=True)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qmain.Task')),
            ],
        ),
    ]
